/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/calc-base.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['calculator-base001'].geometry} material={materials.baseMaterial} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['calculator-base002'].geometry} material={materials.buttonsBaseMaterial} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['calculator-base003'].geometry} material={materials.displayMaterial} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['calculator-base004'].geometry} material={materials.signMaterial} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['calculator-base005'].geometry} material={materials.dropMaterial} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['calculator-base006'].geometry} material={materials.dropButtonMaterial} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/calc-base.gltf')
